### ISSUE TITLE
S3 Access Denied

### ISSUE THREAD

**Issue by elwin-jacellc** [tilezen/tapalcatl-py#44]
We're getting errors while trying to access the S3 zip files. Is the S3 bucket still valid?

server.UnknownMetatileException: AccessDenied at s3://vector-tiles-prod/20171221/42ec2/all/11/328/791.zip

**Comment by iandees** [comment]
The bucket is still valid and we haven't made any changes. Are you seeing it on all tiles or just one or two?

**Comment by elwin-jacellc** [comment]
Its every tile I try to access. Its probably a configuration error on my part but not sure what I'm doing wrong. I've set aws region to us-east-1 and credentials are working for other S3 buckets.

Trying to access via s3 CLI with following commands yields same Access Denied error.

> aws s3api get-object --bucket vector-tiles-prod --key 20171221/all/11/331/794.zip --request-payer requester out.zip
> 
> An error occurred (AccessDenied) when calling the GetObject operation: Access Denied

Tried a different patter via S3 CLI:

> aws s3api get-object --bucket vector-tiles-prod --key 20171221/0/0/0.zip --request-payer requester out.zip
> 
> An error occurred (AccessDenied) when calling the GetObject operation: Access Denied

I've also tried to list-objects command that also generated same error.

> aws s3api list-objects-v2 --bucket vector-tiles-prod --request-payer requester
> 
> An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied

**Comment by iandees** [comment]
The `vector-tiles-prod` bucket doesn't have anything in it anymore. You could try swapping out to `nextzen-meta-tiles-us-east-1`.

**Comment by elwin-jacellc** [comment]
Thanks for that. I've updated the bucket and prefix environment variables but the existing code doesn't request the appropriate keys on S3 any more. With the aws s3api list-object command, I was able to see and download some meta tiles like this key.

> 00000/190701v18a/12/3568/93.zip

Setting the new prefix to 00000, the layer to null, and INCLUDE_HAS to true, the existing code still does not produce the correct hash 190701v18a for this Z/X/Y.zip coordinate.

While we are no longer getting access denied error, we are getting no meta tile found error:

> "No metatile found at s3://%s/%s" % (s3_bucket, s3_key)
> server.MetatileNotFoundException: No metatile found at s3://nextzen-meta-tiles-us-east-1/00000/79f88/11/328/791.zip

**Comment by iandees** [comment]
Try these settings:

```
            "S3_PREFIX": "190701v18a",
            "S3_BUCKET": "nextzen-meta-tiles-us-east-1",
            "REQUESTER_PAYS": "true",
            "METATILE_SIZE": "8",
            "METATILE_MAX_DETAIL_ZOOM": "13",
            "KEY_FORMAT_TYPE": "HASH_PREFIX",
            "S3_LAYER": "",
```

**Comment by elwin-jacellc** [comment]
That did it. Thanks!

**Comment by elwin-jacellc** [comment]
Was able to deploy to Lamda successfully with Zappa on the local machine, but getting errors on Cloudwatch:

```
module 'server' has no attribute 'app': AttributeError
Traceback (most recent call last):
  File "/var/task/handler.py", line 655, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 249, in lambda_handler
    handler = global_handler or cls()
  File "/var/task/handler.py", line 149, in __init__
    wsgi_app_function = getattr(self.app_module, self.settings.APP_FUNCTION)
AttributeError: module 'server' has no attribute 'app
```

Here's our zappa_settings.json

```json
{
    "dev": {
        "app_function": "server.app",
        "aws_region": "us-east-1",
        "project_name": "tapalcatlpy",
        "runtime": "python3.6",
        "debug": true,
        "s3_bucket": "jace-zappa-test",
        "route53_enabled": false,
        "memory_size": 128,
        "environment_variables": {
            "CACHE_TYPE": "filesystem",
            "CACHE_DIR": "/tmp/filecache",
            "CACHE_MAX_AGE": "3600",
            "SHARED_CACHE_MAX_AGE": "1800",
            "TILES_URL_BASE": "/dev",
            "KEY_FORMAT_TYPE": "HASH_PREFIX",
            "S3_PREFIX": "190701v18a",
            "S3_BUCKET": "nextzen-meta-tiles-us-east-1",
            "S3_LAYER": "",
            "REQUESTER_PAYS": "true",
            "METATILE_SIZE": "8",
            "METATILE_MAX_DETAIL_ZOOM": "16"
        }
    },
    "prod": {
        "extends": "dev",
        "debug": false,
        "log_level": "WARN",
        "environment_variables": {
            "CACHE_TYPE": "filesystem",
            "CACHE_DIR": "/tmp/filecache",
            "CACHE_MAX_AGE": "259200",
            "SHARED_CACHE_MAX_AGE": "21600",
            "TILES_URL_BASE": "",
            "KEY_FORMAT_TYPE": "HASH_PREFIX",
            "S3_PREFIX": "190701v18a",
            "S3_BUCKET": "nextzen-meta-tiles-us-east-1",
            "S3_LAYER": "",
            "REQUESTER_PAYS": "true",
            "METATILE_SIZE": "8",
            "METATILE_MAX_DETAIL_ZOOM": "16"
        }
    }
}
```

**Comment by iandees** [comment]
Change `"app_function": "server.app",` to `"app_function": "wsgi_server.app",`

**Comment by elwin-jacellc** [comment]
Any thoughts on this error:

```
[1645302060999] [ERROR] 2022-02-19T20:21:00.997Z a4d02bc2-032f-445b-9c9a-43f7cf15f686 Exception on /tilezen/vector/v1/256/all/13/1312/3164.mvt [GET]
Traceback (most recent call last):
  File "/var/task/flask/app.py", line 2073, in wsgi_app
  response = self.full_dispatch_request()
  File "/var/task/flask/app.py", line 1518, in full_dispatch_request
  rv = self.handle_user_exception(e)
  File "/var/task/flask_cors/extension.py", line 165, in wrapped_function
  return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/var/task/flask/app.py", line 1516, in full_dispatch_request
  rv = self.dispatch_request()
  File "/var/task/flask/app.py", line 1502, in dispatch_request
  return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/var/task/server.py", line 334, in handle_tile
  storage_result = retrieve_tile(meta, offset, request_cache_info)
  File "/var/task/server.py", line 292, in retrieve_tile
  metatile_data = metatile_fetch(meta, cache_info)
  File "/var/task/server.py", line 196, in metatile_fetch
  cached = cache.get(meta)
  File "/var/task/flask_caching/__init__.py", line 263, in get
  return self.cache.get(*args, **kwargs)
  File "/var/task/flask_caching/backends/filesystemcache.py", line 172, in get
  filename = self._get_filename(key)
  File "/var/task/flask_caching/backends/filesystemcache.py", line 165, in _get_filename
  hash = self._hash_method(key).hexdigest()
TypeError: object supporting the buffer API required
```

**Comment by iandees** [comment]
Not sure. Maybe try changing the config to `CACHE_TYPE: simple` to use a memory cache?

**Comment by elwin-jacellc** [comment]
Thanks! We'll submit a PR to update with new settings.
