### ISSUE TITLE
Make it possible to do Requester Pays requests

### ISSUE THREAD

**Issue by boldtrn** [tilezen/tapalcatl-py#8]
Thanks for this awesome repository and your great work. I just had a look at this repo and wanted it to set it up to work with a requester pays bucket on S3.

I think this would be fixable by changing:
```
    get_params = {
        "Bucket": s3_bucket,
        "Key": s3_key,
    }
``` 
to:
```
    get_params = {
        "Bucket": s3_bucket,
        "Key": s3_key,
        "RequestPayer": "requester",
    }
```

Obviously not everyone needs this feature, so it would make sense to make this configurable :).

**Comment by iandees** [comment]
This would be a great pull request if you're up to it. Bonus points for only adding the `RequestPayer` key if it's enabled in [the app's settings](https://github.com/tilezen/tapalcatl-py/blob/master/config.py).

**Comment by boldtrn** [comment]
> This would be a great pull request if you're up to it

I currently don't have a matching bucket to test a PR. I can create a PR once I have a matching bucket to test it.

**Comment by iandees** [comment]
I just flipped the `us-east-1` bucket named `vector-tiles-prod` over to requester pays. We'll have a blog post up soon about how to use this code with that bucket to get tiles 👍 .
